name:               "Fabian"
description:        "Here i will blog about my internship @Crate.io"

url:                ""
author:             "Fabian Reisegger"
email:              "fabian@crate.io"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "fabian@crate.io"
github:             "taliik"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "taliik"

background:         ""

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
